Tsmatrixlib
RocketChat/Rocket.Chat.Federation pull request #15
Opened 2017-06-09 18:52 UTC by madguy02

2017-06-09 21:20 UTC, Sing-Li requested changes
Have you tried running tests with this yet?  Can we add a couple of test to make sure it works.

2017-06-09 21:27 UTC, Sing-Li commented
Please also move the readme over, as per our discussions.  And remove the old directory.

2017-06-11 06:17 UTC, madguy02 commented
@Sing-Li one set of test added to test_ts and transpilation automated with npm run build.

2017-06-11 12:45 UTC, Sing-Li commented
Please add sections on README.  Let a new contributor know how to:

* check out your branch
* build the code
* run the tests

Please make sure your instructions actually work - by checking out your code on a clean machine, VM, or VPS.

2017-06-11 20:13 UTC, Sing-Li requested changes

2017-06-11 20:13 UTC, Sing-Li commented on tsmatrixserverlib/Readme.md
> +git clone<repository>.
`git clone` what?  Please be precise, for someone starting from scratch on a new system.

2017-06-11 20:13 UTC, Sing-Li commented on tsmatrixserverlib/Readme.md
> +git checkout branchname(tsmatrixlib).
if it is going to be `tsmatrixlib`, then use `tsmatrixlib`.  This should be explicit instruction that works.

2017-06-11 20:13 UTC, Sing-Li commented on tsmatrixserverlib/Readme.md
> +npm run start
There is no server to "run".   You are creating a lib that is an npm module.  Ideally, it should build the module off an npm command.

2017-06-11 20:18 UTC, Sing-Li requested changes

2017-06-11 20:18 UTC, Sing-Li commented on tsmatrixserverlib/test_ts/hello_test.ts
> +describe('Hello function', () => {
Let's not bring in "hello" test, and use some of the tests that you've written already.

The JS tests you've already written should pass, as well as new "type enforced" TS tests that you'll add.

2017-06-15 10:11 UTC, Sing-Li approved these changes

2017-06-15 10:12 UTC, Sing-Li commented
`npm test` currently only run the TS tests.    

Can you please add instructions (workflow) on running the JS tests as well.

2017-06-16 13:13 UTC, Sing-Li commented
`setup_XX.sh` actually **run** the tests , really should be  named `run_XX.sh` 

But right now, the JS one does not work `./setup_JS.sh: line 3: mocha: command not found`

We really should have `npm test` run both TS and JS tests, and not separate shell scripts that the users have to run.

2017-06-16 13:15 UTC, madguy02 commented
Okay I will correct it ASAP

2017-06-16 16:44 UTC, madguy02 commented
@Sing-Li  changes pushed

2017-06-18 12:45 UTC, madguy02 commented
@Sing-Li  please check whether this test directory stucture is proper

2017-06-18 14:23 UTC, Sing-Li commented
@madguy02    any reason why you're preceeding with`test_` again?  these subdir are already under the `test` subdirectory.   Secondly, `npm test` currently does not work as of this commit.

2017-06-18 19:36 UTC, Sing-Li commented
Excellent!   Let me know if you want a merge down for the interim.

2017-06-19 01:20 UTC, madguy02 commented
Yeah @Sing-Li .. a merge down will help,as I was planning to start another PR on the rest of the module development.

2017-06-19 03:44 UTC, merged